"""Add foreign key indexes for print management.

Revision ID: 05a73f52ae66
Revises: 1b7595f9cb0f
Create Date: 2026-07-12 03:57:02.781186
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '05a73f52ae66'
down_revision = '1b7595f9cb0f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_plate_project_file_id'), 'plate', ['project_file_id'], unique=False)
    op.create_index(op.f('ix_plate_project_id'), 'plate', ['project_id'], unique=False)
    op.create_index(op.f('ix_print_job_plate_id'), 'print_job', ['plate_id'], unique=False)
    op.create_index(op.f('ix_print_job_printer_id'), 'print_job', ['printer_id'], unique=False)
    op.create_index(op.f('ix_print_job_spool_print_job_id'), 'print_job_spool', ['print_job_id'], unique=False)
    op.create_index(op.f('ix_print_job_spool_spool_id'), 'print_job_spool', ['spool_id'], unique=False)
    op.create_index(op.f('ix_project_file_project_id'), 'project_file', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_file_project_id'), table_name='project_file')
    op.drop_index(op.f('ix_print_job_spool_spool_id'), table_name='print_job_spool')
    op.drop_index(op.f('ix_print_job_spool_print_job_id'), table_name='print_job_spool')
    op.drop_index(op.f('ix_print_job_printer_id'), table_name='print_job')
    op.drop_index(op.f('ix_print_job_plate_id'), table_name='print_job')
    op.drop_index(op.f('ix_plate_project_id'), table_name='plate')
    op.drop_index(op.f('ix_plate_project_file_id'), table_name='plate')
    # ### end Alembic commands ###
