"""Move project file link to plate.

Revision ID: 1b7595f9cb0f
Revises: fe54f97ca85b
Create Date: 2026-07-12 02:56:30.817055
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '1b7595f9cb0f'
down_revision = 'fe54f97ca85b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plate') as batch_op:
        batch_op.add_column(sa.Column('project_file_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_plate_project_file', 'project_file', ['project_file_id'], ['id'])
        
    with op.batch_alter_table('project_file') as batch_op:
        batch_op.drop_column('plate_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_file') as batch_op:
        batch_op.add_column(sa.Column('plate_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_project_file_plate', 'plate', ['plate_id'], ['id'])
        
    with op.batch_alter_table('plate') as batch_op:
        batch_op.drop_constraint('fk_plate_project_file', type_='foreignkey')
        batch_op.drop_column('project_file_id')
    # ### end Alembic commands ###
