"""Add print management.

Revision ID: fdc4cb99d052
Revises: 415a8f855e14
Create Date: 2026-07-08 23:12:16.545998
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fdc4cb99d052'
down_revision = '415a8f855e14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('description', sa.String(length=1024), nullable=True),
    sa.Column('link', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_id'), 'project', ['id'], unique=False)
    op.create_table('plate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('estimated_weight', sa.Float(), nullable=True),
    sa.Column('estimated_time', sa.Integer(), nullable=True, comment='Estimated time in seconds'),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plate_id'), 'plate', ['id'], unique=False)
    op.create_table('print_job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered', sa.DateTime(), nullable=False),
    sa.Column('plate_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('printer_name', sa.String(length=256), nullable=True),
    sa.Column('comment', sa.String(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['plate_id'], ['plate.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_job_id'), 'print_job', ['id'], unique=False)
    op.create_table('print_job_spool',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('print_job_id', sa.Integer(), nullable=False),
    sa.Column('spool_id', sa.Integer(), nullable=False),
    sa.Column('weight_used', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['print_job_id'], ['print_job.id'], ),
    sa.ForeignKeyConstraint(['spool_id'], ['spool.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_print_job_spool_id'), 'print_job_spool', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_print_job_spool_id'), table_name='print_job_spool')
    op.drop_table('print_job_spool')
    op.drop_index(op.f('ix_print_job_id'), table_name='print_job')
    op.drop_table('print_job')
    op.drop_index(op.f('ix_plate_id'), table_name='plate')
    op.drop_table('plate')
    op.drop_index(op.f('ix_project_id'), table_name='project')
    op.drop_table('project')
    # ### end Alembic commands ###
