"""Add project_file table.

Revision ID: fe54f97ca85b
Revises: c0e86b24d77b
Create Date: 2026-07-11 21:24:12.654556
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fe54f97ca85b'
down_revision = 'c0e86b24d77b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('registered', sa.DateTime(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=256), nullable=False),
    sa.Column('file_path', sa.String(length=1024), nullable=True),
    sa.Column('size', sa.Integer(), nullable=True),
    sa.Column('plate_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['plate_id'], ['plate.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_file_id'), 'project_file', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_file_id'), table_name='project_file')
    op.drop_table('project_file')
    # ### end Alembic commands ###
